"""esquema inicial: empresa, matriz, plan, kpi, cmi

Revision ID: 7c3f6280e8d5
Revises: 
Create Date: 2026-07-07 12:14:33.649116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c3f6280e8d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('mision', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matriz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('holmes', 'foda_cuali', 'foda_cuanti', 'efi', 'efe', 'cadena_valor', 'aoor', 'aprovechabilidad', 'cinco_fuerzas', 'mpc', 'ansoff', 'pestel', 'peyea', 'madi', 'made', name='tipomatriz'), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perspectiva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('financiera', 'clientes', 'procesos', 'aprendizaje', name='tipoperspectiva'), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('financiero', 'marketing', 'operaciones', 'mejoras', 'tecnologico', 'compras', 'control', name='tipoplan'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premisas_financieras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('inflacion', sa.Float(), nullable=False),
    sa.Column('crecimiento_ventas', sa.Float(), nullable=False),
    sa.Column('impuestos', sa.Float(), nullable=False),
    sa.Column('wacc', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estrategia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('tipo_estrategia', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factor_matriz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('calificacion', sa.Float(), nullable=True),
    sa.Column('resultado', sa.Float(), nullable=True),
    sa.Column('extra_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['matriz_id'], ['matriz.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objetivo_cmi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perspectiva_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=False),
    sa.ForeignKeyConstraint(['perspectiva_id'], ['perspectiva.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actividad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrategia_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=400), nullable=False),
    sa.Column('responsable', sa.String(length=200), nullable=True),
    sa.Column('tiempo', sa.String(length=100), nullable=True),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('tipo_cuenta', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['estrategia_id'], ['estrategia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estrategia_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('formula', sa.String(length=400), nullable=True),
    sa.Column('frecuencia', sa.String(length=50), nullable=True),
    sa.Column('ponderacion', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['estrategia_id'], ['estrategia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indicador_cmi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('objetivo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('meta', sa.Float(), nullable=False),
    sa.Column('ponderacion', sa.Float(), nullable=True),
    sa.Column('rango_min', sa.Float(), nullable=True),
    sa.Column('rango_max', sa.Float(), nullable=True),
    sa.Column('sentido', sa.Enum('directo', 'inverso', name='sentido'), nullable=False),
    sa.ForeignKeyConstraint(['objetivo_id'], ['objetivo_cmi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('tipo_periodo', sa.Enum('mensual', 'trimestral', 'semestral', 'anual', 'ciclo_cosecha', name='tipoperiodo'), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicador_cmi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicion')
    op.drop_table('indicador_cmi')
    op.drop_table('indicador')
    op.drop_table('actividad')
    op.drop_table('objetivo_cmi')
    op.drop_table('factor_matriz')
    op.drop_table('estrategia')
    op.drop_table('premisas_financieras')
    op.drop_table('plan')
    op.drop_table('perspectiva')
    op.drop_table('matriz')
    op.drop_table('empresa')
    # ### end Alembic commands ###
